#!/bin/zsh

#set -x

loggedInUser=$(ls -l /dev/console | awk '{print$3}')
#localUser=$(who | awk '{print $1}')
mkdir -p "/Users/$loggedInUser/Library/Application Support/Epic/EpicGamesLauncher/Data"
cp -R "/Users/LOCALADMIN/Library/Application Support/Epic/EpicGamesLauncher/Data/Manifests" "/Users/$loggedInUser/Library/Application Support/Epic/EpicGamesLauncher/Data/"
cp "/Users/LOCALADMIN/Library/Preferences/com.epicgames.EpicGamesModSdk.plist" "/Users/$loggedInUser/Library/Preferences"
cp "/Users/LOCALADMIN/Library/Preferences/com.epicgames.EpicWebHelper.plist" "/Users/$loggedInUser/Library/Preferences"
