#!/bin/zsh

#set -x

loggedInUser=$(ls -l /dev/console | awk '{print$3}')
mkdir -p "/Users/$loggedInUser/Library/Application Support/Epic/EpicGamesLauncher/Data"
cp -R "/Users/LOCALADMIN/Library/Application Support/Epic/EpicGamesLauncher/Data/Manifests" "/Users/$loggedInUser/Library/Application Support/Epic/EpicGamesLauncher/Data/"
